# Generated by Django 2.0.4 on 2018-05-19 15:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('licenseplate', models.CharField(max_length=200)),
                ('doors', models.CharField(max_length=200)),
                ('seats', models.CharField(max_length=200)),
                ('booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frombooked', models.DateField(default=datetime.date.today)),
                ('tobooked', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(default='Aggiungi note..')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.Car')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4)])),
                ('last_login', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='carbooked',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApp.User'),
        ),
    ]
