# Generated by Django 2.0.4 on 2018-05-19 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarApp', '0002_auto_20180520_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooked',
            name='username',
        ),
        migrations.AddField(
            model_name='carbooked',
            name='username',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
