# Generated by Django 2.0.4 on 2018-05-19 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarApp', '0003_auto_20180520_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooked',
            name='username',
        ),
        migrations.AddField(
            model_name='carbooked',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
