# Generated by Django 2.0.4 on 2018-05-20 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0004_auto_20180520_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='frombooked',
            field=models.DateField(default=datetime.date.today, verbose_name='Da'),
        ),
    ]
