# Generated by Django 2.0.4 on 2018-05-20 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0005_auto_20180520_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooked',
            name='place',
            field=models.CharField(default=1, max_length=10, verbose_name='Dove?'),
        ),
        migrations.AlterField(
            model_name='carbooked',
            name='tobooked',
            field=models.DateField(default=datetime.date.today, verbose_name='a'),
        ),
    ]
