# Generated by Django 2.0.4 on 2018-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0006_auto_20180520_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='place',
            field=models.CharField(default=None, max_length=10, verbose_name='Dove?'),
        ),
    ]
