# Generated by Django 2.0.4 on 2018-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0007_auto_20180520_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='place',
            field=models.CharField(max_length=30, verbose_name='Dove?'),
        ),
    ]
