# Generated by Django 2.0.4 on 2018-05-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0008_auto_20180520_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='booked',
        ),
    ]
