# Generated by Django 2.0.4 on 2018-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0009_remove_car_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooked',
            name='note',
            field=models.TextField(default=None),
        ),
    ]
