# Generated by Django 2.0.4 on 2018-05-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0011_carbooked_booked_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooked',
            name='booked_or_not',
        ),
    ]
